version: '3.9'

services:
  backend:
    build: ./backend
    container_name: spring-boot-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80" # ✅ Map local 3000 -> container 80 (Nginx serves on 80)
    restart: always


